### Sampling Schemes

library(PsyFuns)
# The reasons are modeled after Wichman,Hill paper and book
# Sampling schemes are defined in ordinal values for inner function

# They are generated by INNER WEIBULL FUNCTION: F = 1 - e^((x/a)^b)
# with parameters: a=8.85/((log(2)^(1/3))), b=3
pars <- c(8.85/((log(2)^(1/3))), 3)
OrdToAbs <- function(ordinates){
  PsyFuns:::polynom.inverse_x.cdf(
    PsyFuns:::exponential.inverse.cdf(
      ordinates), 
      pars)
}

#midpoint <- function(x){(x[1] + x[length(x)])/2}

# performance threshold is set to 8.85
perf_th <- OrdToAbs(0.5) 
perf_th
# 
#Interquartile range is set to 4.5
iqr <- OrdToAbs(0.75) - OrdToAbs(0.25)
iqr
#
# Width range is set to 10.7
width <- OrdToAbs(0.95) - OrdToAbs(0.05)
width

#s1 - symetric close
# Ordinal values of s1 (0.3,0.4,0.48,0.52,0.6,0.7)
o1 <- c(0.3,0.4,0.48,0.52,0.6,0.7)
x1 <- OrdToAbs(o1)
x1 <- round(x1,2)
x1

#s2 - symetric apart
# Ordinal values of s2 (0.1,0.3,0.40,0.6,0.7,0.9)
o2 <- c(0.1,0.3,0.40,0.6,0.7,0.9)
x2 <- OrdToAbs(o2)
x2 <- round(x2,2)
x2

#s3 - nonsymetric skewed towards high performance
# Ordinal values of s3 (0.3,0.44,0.7,0.8,0.9,0.98)
o3 <- c(0.3,0.44,0.7,0.8,0.9,0.98)
x3 <- OrdToAbs(o3)
x3 <- round(x3,2)
x3

#s4 - nonsymetric skewed towards low performance
# Ordinal values of s4 (0.1,0.2,0.3,0.4,0.5,0.6)
o4 <- c(0.1,0.2,0.3,0.4,0.5,0.6)
x4 <- OrdToAbs(o4)
x4 <- round(x4,2)
x4

#s5 - nonsymetric skewed towards high performance
# Ordinal values of s5 (0.08,0.18,0.28,0.70,0.85,0.99)
o5 <- c(0.08,0.18,0.28,0.70,0.85,0.99)
x5 <- OrdToAbs(o5)
x5 <- round(x5,2)
x5

#s6 - nonsymetric closely disperse, one outlier
# Ordinal values of s6 (0.3,0.4,0.5,0.6,0.7,0.99)
o6 <- c(0.3,0.4,0.5,0.6,0.7,0.99)
x6 <- OrdToAbs(o6)
x6 <- round(x6,2)
x6

#s5 - nonsymetric skewed towards high performance
# Ordinal values of s7 (0.34,0.44,0.54,0.8,0.9,0.98)
o7 <- c(0.34,0.44,0.54,0.8,0.9,0.98)
x7 <- OrdToAbs(o7)
x7 <- round(x7,2)
x7

